[CommonSettings]
SourcePath=./Content/Localization/rebocap
DestinationPath=./Content/Localization/rebocap
ManifestName=rebocap.manifest
ArchiveName=rebocap.archive
ResourceName=rebocap.locres
PortableObjectName=rebocap.po
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=zh-Hans
CulturesToGenerate=ja

; Gather text from source code
[GatherTextStep0]
CommandletClass=GatherTextFromSource
SourcePaths=./Source/rebocap_runtime
SourcePaths=./Source/rebocap_editor
SourcePaths=./Source/rebocap
FileNameFilters=*.h
FileNameFilters=*.cpp

; Generate manifest
[GatherTextStep1]
CommandletClass=GenerateTextManifest

; Generate archives
[GatherTextStep2]
CommandletClass=GenerateTextArchives

; Export to PO
[GatherTextStep3]
CommandletClass=InternationalizationExportPO

; Import from PO
[GatherTextStep4]
CommandletClass=InternationalizationImportPO

; Generate compiled LocRes
[GatherTextStep5]
CommandletClass=GenerateTextLocalizationResource
